ДЗ 2.1
htmlacademy-htmlcss/1684973-sedona-30 pull request #2
Opened 2021-02-09 18:50 UTC by bynbynbyn

(1) Шрифт так и не поборол - подскажите, что делаю не так, плз.

(2) На графику пока не обращайте внимания - там очень многое не так, как надо бы.

(3) Фон страницы задал просто, чтобы все элементы были видны.

Regards,
BYN

2021-02-10 15:59 UTC, andreysgra requested changes
Вот этот [пункт ТЗ](https://up.htmlacademy.ru/htmlcss/30/project/sedona#sedona-3-12): вам нужно эти элементы разметить с помощью `button type="button"`:

![image](https://user-images.githubusercontent.com/17790771/107535707-09674880-6bd2-11eb-8b02-b38490b29c65.png)

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +    </style><!-- text-transform: uppercase;-->
Стили не нужно подключать в разметке с помощью тега `<style>`. Всё пишем в файле **styles.css**.

На данный момент вообще советую не подключать шрифты, так как это уже 4-е задание. Всему своё время.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +          <li><a href="htmlpages/hotels.html">Гостиницы</a></li>
1. Все html файлы должны лежат в корне сайта, как и **index.html**. Не нужно создавать для них отдельную директорию.
2. Для страниц, которые мы не верстаем достаточно создать один файл-заглушку **blank.html**. Нет необходимости создавать таковые для каждой страницы. Итого, в вашем проекте будет 3 файла: **index.html**, **hotels.html**, **blank.html**.
3. Требований для создания файла-заглушки нет, но если вы пошли по этому пути, то в **blank.html** должны присутствовать общие для всего проекта блоки: шапка и подвал.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +        <img src="img/zigzag.svg" alt="">
Это одно целое изображение

![image](https://user-images.githubusercontent.com/17790771/105631823-71433280-5e61-11eb-9677-93ab07b523b1.png)

Не нужно его дробить на три части.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +          <img src="img/Rectangle_for_tytle.svg" alt="">
Это явно что-то лишнее. У нас нет такого изображения.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +      </section>
У вас не очень удачная разметка данного блока:

![image](https://user-images.githubusercontent.com/17790771/105632026-3f7e9b80-5e62-11eb-8ef9-a167d6699421.png)

Его можно разметить списком (обвёл синим цветом). Красным цветом обведены элементы списка. Их пять, как и причин, по которым стоит поехать в седону. Внутри первого элемента списка будет находится другой, вложенный список (обведён зелёным), который состоит из трёх элементов.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +        <img src="img/Rectangle-advantages.svg" alt="">
Это явно что-то лишнее. У нас нет такого изображения.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +        <img src="img/Rectangle-advantages.svg" alt="">
Это явно что-то лишнее. У нас нет такого изображения.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +        <img src="img/map.png" alt="">
Карта в разметке должна находится ниже формы. То, что форма в макете расположена над картой - это дело CSS, а не HTML.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +        <button class="form-title">ПОИСК ГОСТИНИЦЫ В седоне</button>
1. Нужно явно указать тип кнопки, так как по умолчанию он равен `submit`. В данном случае это `type="button"`.
2. Не пишите текст в разметке заглавными буквами. Это нехорошо. За внешний вид отвечает CSS, а HTML за логику документа.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +              <img src="img/calendar-icon.svg" alt=""><br>
Это фоновое изображение и его не нужно добавлять в разметку. Про различия между контентными и фоновыми изображениями можно почитать [здесь](https://htmlacademy.ru/blog/education/all/content-or-decor-img).

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +              <img src="img/calendar-icon.svg" alt=""><br>
Критерий [Б4](https://up.htmlacademy.ru/htmlcss/30/criteries#b4) - недопустимо использовать `<br>` для разбиения текста на абзацы.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +              <img src="img/calendar-icon.svg" alt=""><br>
Это фоновое изображение и его не нужно добавлять в разметку. Про различия между контентными и фоновыми изображениями можно почитать [здесь](https://htmlacademy.ru/blog/education/all/content-or-decor-img).

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +              <img src="img/calendar-icon.svg" alt=""><br>
Критерий [Б4](https://up.htmlacademy.ru/htmlcss/30/criteries#b4) - недопустимо использовать `<br>` для разбиения текста на абзацы.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +              <input class="text" value="-">
`button type="button"`

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +              <input class="text" value="+">
`button type="button"`

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +            <input class="text" value="-">
`button type="button"`

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +              <input class="text" value="+">
`button type="button"`

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +            <input type="submit" value="найти" class="find-button">
`button type="submit"`

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +          <P>ТЕЛ: +7(495) 666-01-66</P>
[Д29](https://up.htmlacademy.ru/htmlcss/30/criteries#d29)

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +          <P>ТЕЛ: +7(495) 666-01-66</P>
Для тегов нужно использовать строчные буквы (у вас `<p>` написан заглавными).

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +      <div> <!--Соц. сети-->
Этот `div` явно лишний. Стоит убрать из разметки.

2021-02-10 15:59 UTC, andreysgra commented on index.html
> +              <img src="img/twitter.svg" alt="Твиттер">
Для иконки соцсети используется одно изображение. Синий квадрат реализуется средствами CSS.

2021-02-16 07:53 UTC, andreysgra requested changes
Папку **htmlpages** вместе с её содержимым нужно удалить.

2021-02-16 07:53 UTC, andreysgra commented on index.html
> +          </li>
Этот блок не нужно выделять в отдельный элемент списка. Данный список будет находиться внутри `li` первой причины:
```
<li>
  <h2>Настоящий<br>городок</h2>
  <p>— №1 —</p>
  <p>Седона - не аттракцион для туристов, там<br>течёт своя жизнь</p>
  <img src="img/sedona-cafe.jpg" alt="">

  <ul>
    <li><!---Жилье-->
      <img src="img/lodging-icon.svg" class="white-background" alt="">
      <h2>Жилье</h2>
      <p>Рекомендуем пожить в настоящем<br>мотеле, всё как в кино!</p>
    </li>
    <!--Еда-->
    <!--Сувениры-->
  </ul>
</li>
```

2021-02-16 08:32 UTC, bynbynbyn commented on index.html
> +          </li>
Логично. Исправил.

2021-02-16 08:33 UTC, bynbynbyn commented
Удалил.

2021-02-17 18:18 UTC, andreysgra requested changes

2021-02-17 18:18 UTC, andreysgra commented on catalog.html
> +            <h3>инфраструктура:</h3>
Рекомендация: есть специальные теги формы - `fieldset` и `legend`. Тег `fieldset` используется для группирования схожих по предназначению полей формы, а тег `legend` используется для создания заголовка внутри `fieldset`.

Соответственно этот код можно переписать так:
```suggestion
          <fieldset>
            <legend>инфраструктура:</legend>
```

2021-02-17 18:18 UTC, andreysgra commented on catalog.html
> +            <button type="button" name="by-rate">по рейтингу</button>
Нужно разметить не кнопками, а ссылками.

2021-02-17 18:18 UTC, andreysgra commented on catalog.html
> +            </button>
Нужно разметить не кнопками, а ссылками.

2021-02-17 18:18 UTC, andreysgra commented on catalog.html
> +            </form>
Данный блок не является формой. `form` нужно заменить на `div`, а кнопки "подробнее" и "забронировать" заменить на ссылки.

2021-02-17 18:18 UTC, andreysgra commented on catalog.html
> +              <p>апартвменты</p>
```suggestion
              <p>апартаменты</p>
```

2021-02-17 18:18 UTC, andreysgra commented on catalog.html
> +                <img src="img/star.svg" alt="star">
Для группы изображений значение `alt` указывается для первого изображения, как в [этом примере](https://www.w3.org/WAI/tutorials/images/groups/).

2021-02-18 17:07 UTC, merged